### PR TITLE
open sourcerize

### PR DESCRIPTION
**Pull request by thebyrd**
Hello @sjkaliski, 

Please review the following commits I made in branch 'thebyrd-open-sourcerize'.

733de21943e480330fccfb0e08eae92bef11de72 (2015-02-03 13:46:34 -0500)
open sourcerize

R=@sjkaliski
VISIBLE_CHANGES=open sourcerize

### CODE REVIEW

**Comment by sjkaliski** [comment]
:100:

**Comment by thebyrd** [comment]
@sjkaliski The fact that I haven't gotten an LGTM yet from you closed source pigs is evidence of how open source is dead. Please level up.

**Comment by sjkaliski** [comment]
Hi @thebyrd,

Thanks for your pull-request. On behalf of the authors of this repository, I'd like to point you to some documentation on pull-requests https://github.com/sjkaliski/squad/blob/master/CONTRIBUTING.md.

Hopefully this will clear up any confusion.

Thanks,
Steve

**Comment by thebyrd** [comment]
Should I re-submit?

**Comment by sjkaliski** [comment]
Typically I'd request that, but in this particular circumstance I'll let it slide.

Keep it :100:

**Comment by thebyrd** [comment]
:pray: bless up G

**Comment by FrancescaK** [comment]
i wish I could like this

**Pull request merged**
